### ISSUE TITLE
?

### ISSUE THREAD

**Issue by hajimura** [theAsmodai/ReInfoZone#2]
Any activity?

**Comment by theAsmodai** [comment]
If you want activity - create zones for all popular maps.

**Comment by hajimura** [comment]
Ok

**Comment by ish12321** [comment]
Any activity now?

**Comment by theAsmodai** [comment]
Some peoples wanted to create zones for these module, but they never did it.

**Comment by ish12321** [comment]
Hmm..  Cant we not use the zones of cz? Maps are almost same.. :/

**Comment by ish12321** [comment]
?

**Comment by ish12321** [comment]
Bump!

**Comment by ish12321** [comment]
Ready now after your commits?
