### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by ish12321** [theAsmodai/ReInfoZone#6]
Recently a crash occurred. I after put this .. Not sure why as no logs but if you could check once it'll be greatful..

**Comment by theAsmodai** [comment]
Ok, I need a crash dump.

**Comment by ish12321** [comment]
How to get that?

**Comment by theAsmodai** [comment]
Launch HLDS with `ulimit -c unlimited && ./hlds_run -debug ...`

**Comment by ish12321** [comment]
In windows in preoperties after the path what things are to be written?

**Comment by theAsmodai** [comment]
For windows check one of this manuals:
http://aghl.ru/forum/viewtopic.php?p=21528#p21528
http://aghl.ru/forum/viewtopic.php?p=23876#p23876
